# Generated by Django 3.2 on 2021-05-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_courier_job_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent_id',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
    ]
